### PR TITLE
Added window to phantom

### PR DESCRIPTION
**Pull request by ArnaudBuchholz**
First, sorry for all that mess...

Then, I found that window was missing in phantom environment.

- Arnaud

### CODE REVIEW

**Comment by sindresorhus** [comment]
Not sure about this. I assumed `phantomjs` was intended to expose things not already exposed by `browser` and `builtin`. If that's the case, `console` should probably don't be there either.

**Comment by ArnaudBuchholz** [comment]
OK but, in the context of using ESLint: there is a difference between setting the environment to browser and phantomjs.
I would expect the environment to contain everything needed. I shouldn't need to set both environement. Furthermore, browser may expose things that are not available to phantomjs.

Am I clear?

**Comment by nzakas** [comment]
`phantomjs` is for PhantomJS scripts vs. scripts that run in a browser.

**Comment by pmcelhaney** [comment]
ESLint allows multiple environments to be configured. What's wrong with this?

    {
        "env": {
            "browser": true,
            "phantomjs": true
        }
    },

If you need the PhantomJS globals and `window` (but not other browser globals) you can get it like this.

    {
        "env": {
            "phantomjs": true
        }
    },  {
        "globals": {
            "window": false
        }
    }

**Comment by ArnaudBuchholz** [comment]
Well, this is what I did but then, why do I care about specifying phantomjs? I could define everything as globals ;-)
To me, the point is to provide the exact environment so that the correct globals are defined.
window is actually exposed by phantomJs: hence it should be a global of phantomjs.

**Comment by nzakas** [comment]
@ArnaudBuchholz is there a list of all PhantomJS globals somewhere? I think there's some confusion as to whether `window` is actually part of the PhantomJS script environment or if it's leaked from the browser. Seeing a definitive list could end that confusion.

**Comment by ArnaudBuchholz** [comment]
Actually, phantomJS **is** a browser but with restrictions (for instance, AFAIK, the FileReader API is not yet ready) but I don't have the exact list of globals. window is exposed for sure.

**Comment by pmcelhaney** [comment]
That's my understanding as well. PhantomJS is a browser. It's a headless browser, but it's still a browser. It's therefore no different from Chrome or Firefox or IE, which also may or may not support some of the newer APIs. Those other browsers don't have their own configs, so what makes Phantom special?

If you're developing for browsers, you can use the "browser" environment as a convenience. If you want to be precise, you should explicitly declare which globals your app uses. Given varying support matrixes, polyfills, and features, the precise list is going to be different for every app.

**Comment by nzakas** [comment]
@ArnaudBuchholz  There's a slight but important difference between what you're saying and what I'm saying.

PhantomJS is comprised of *two* JavaScript runtimes. There's the one in the browser (and hence, has all the browser globals), but there's also the scripting engine you use to script PhantomJS. For instance: https://github.com/ariya/phantomjs/blob/master/examples/arguments.js

This script does not run within the browser, instead it runs in PhantomJS's scripting engine.

The `phantomjs` entry in `globals` refers only to the latter, so before can add `window`, we need to know that it actually exists there.

**Comment by ArnaudBuchholz** [comment]
@pmcelhaney Fair enough, I could use both
@nzakas I understand your point but, indeed, the window global is available in both environments

**Pull request closed without merging**
