### PR TITLE
Add `structuredClone` for browser.

### PR DESCRIPTION
**Pull request by regseb**
Add [`structuredClone`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) for _browser_ (and _shared-node-browser_).

### CODE REVIEW

**Review by aladdin-add — CHANGES_REQUESTED** [review]
it's also available in node.js/worker?

**Comment by regseb** [comment]
> it's also available in node.js/worker?

The [MDN compatibility](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone#browser_compatibility) indicates that `structuredClone` isn't available in Node.js workers.

**Comment by aladdin-add** [comment]
well, I see. and it's has been added to node.js in https://github.com/sindresorhus/globals/pull/182.

**Review by aladdin-add — APPROVED** [review]
LGTM~

**Pull request merged**
