### PR TITLE
fixed #51: window.event should be removed

### LINKED ISSUE #51: window.event should be removed
`window.event` Microsoft-only so should be removed
https://developer.mozilla.org/en-US/docs/Web/API/Window/event

### PR DESCRIPTION
**Pull request by zowers**

### CODE REVIEW

**Comment by sindresorhus** [comment]
:+1:

**Comment by nzakas** [comment]
This would be a breaking change for ESLint :-/

**Comment by sindresorhus** [comment]
We can wait until ESLint 2.0. Though, I doubt anyone is using it in their own code.

**Comment by zowers** [comment]
why is it a breaking change?

**Comment by nzakas** [comment]
Upon review, it looks like Firefox is the only browser that doesn't currently have a global `event` property. So I'm really not sure about removing this.

**Comment by sindresorhus** [comment]
Closing as this was declined in ESLint: https://github.com/eslint/eslint/issues/3964#issuecomment-146594802

**Pull request closed without merging**
