### PR TITLE
Add notOk exposed on QUnit 1.18+

### PR DESCRIPTION
**Pull request by leobalter**

### CODE REVIEW

**Comment by sindresorhus** [comment]
It always help to link to a source when doing a PR so the maintainer doesn't have to try to dig it up.

**Comment by leobalter** [comment]
I'm sorry I did this on the go, I'll update the commit message to include the references.

**Comment by leobalter** [comment]
It's done (on the commit message)

**Comment by sindresorhus** [comment]
Excellent :)

**Pull request merged**
