### PR TITLE
add missing worker globals

### PR DESCRIPTION
**Pull request by silverwind**
Added quite a few properties of the [`worker` global scope](https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope). `onmessage` is actually write-only here, but to represent that, we'd need something more than a boolean :wink:.

### CODE REVIEW

**Comment by sindresorhus** [comment]
The initial thinking was problably that the `worker` be anything not already in `browser`, but this makes more sense.

**Comment by silverwind** [comment]
Well, that page isn't really complete, there's still more available. Maybe it's time to feature-test all globals inside workers.

**Comment by silverwind** [comment]
Shared workers also seem to sport a few globals of their own, and I found a hopefully complete list of available APIs. Should we add all of them?

https://developer.mozilla.org/en-US/docs/Web/API/SharedWorkerGlobalScope
https://developer.mozilla.org/en-US/docs/Web/API/Worker/Functions_and_classes_available_to_workers

**Comment by nzakas** [comment]
:+1:

**Comment by silverwind** [comment]
Alright, think I got them all.

**Comment by sindresorhus** [comment]
Thanks @silverwind :)

**Pull request closed without merging**
