### PR TITLE
Add es5 and es6 environments

### PR DESCRIPTION
**Pull request by nzakas**
This commit adds two new entries: `es5` and `es6`. This will allow people to optionally include just the globals they want depending on the environment without introducing a breaking change (you can still use `builtin` to get them all). 

This is to address: https://github.com/eslint/eslint/issues/4085

### CODE REVIEW

**Comment by es128** [comment]
Should `es6` not be inclusive of everything in `es5`? What would the use case be for `es6` over `builtin`?

**Comment by nzakas** [comment]
Hmmm, good point. I was initially thinking people might use es6 to augment es5, but I think you're right, it seems to make better sense to have es6 be inclusive of es5.

I was thinking for clarity, es6 is obvious as to what it includes. Otherwise, omitting es6 means it would have to be added back if es7 introduces new globals.

**Comment by es128** [comment]
Yeah it's ugly for `globals.json`, but I think inclusive lists probably makes a lot more sense for usability.

One possible way to deal with it - for easier maintenance and ability to reference additive changes - would be to come up with a new schema that denotes supersets (perhaps leave room for other annotations like documentation refs) and then dynamically generate `globals.json` in its existing format with each release from that. Maybe overkill at this point.

**Comment by nzakas** [comment]
Updated. I think generating the sets is probably overkill for the usage. :)

**Pull request merged**
