### PR TITLE
Add Jest globals

### PR DESCRIPTION
**Pull request by dar5hak**
As specified at http://facebook.github.io/jest/docs/api.html#globally-injected-variables

### CODE REVIEW

**Comment by nzakas** [comment]
:+1:

**Comment by dar5hak** [comment]
@nzakas @sindresorhus Thank you.

I am also willing to add a Jest environment to ESLInt. Any chance you could release a new version of `globals`, so that I can make a PR there?

**Comment by sindresorhus** [comment]
@dar5hak v8.3.0.

**Comment by dar5hak** [comment]
@sindresorhus Gracias. :+1:

**Pull request merged**
