### PR TITLE
Build data file

### PR DESCRIPTION
**Pull request by fisker**
Store data in `.mjs` files and generate `globals.json`. I'll try to use js to import and merge data for some environments like `es*` `node` later.

### CODE REVIEW

**Comment by fisker** [comment]
Any suggestion to store data? 

a)

```js
export default {
	name: boolean
};
```

b)

```js
export default [
	'readonly',
	{name: 'foo', writable: true},
	'bar',
];
```

c)

```js
export const globals = ['foo', 'bar'];
export const writable = ['foo'];
```

**Comment by sindresorhus** [comment]
What problem does this solve? Smaller package size?

**Comment by sindresorhus** [comment]
> Any suggestion how to store data?

It depends on what the priority is. Performance or size? `A` is ideal for performance since no transformation has to happen at runtime. `C` is ideal for size.

**Comment by fisker** [comment]
Easier to maintain, for example "nodeBuiltin" now build by script, `node.js` can be simply `{...nodeBuiltin, ...commonjsGlobals}`, so we don't need to build both. `shared-node-browser` can also calculated.

**Comment by fisker** [comment]
> It depends on what the priority is. Performance or size? 

We still build `global.json`, Performance  and size doesn't matter, some of these files will be hand-written, eg "jquery".

**Comment by sindresorhus** [comment]
Then `A` is probably the best format.

**Comment by fisker** [comment]
> Then `A` is probably the best format.

Ready for review then.

**Pull request merged**
