### PR TITLE
Add SpeechRecognition browser global.

### PR DESCRIPTION
**Pull request by sholladay**
This PR also comes with an improved test suite to back it up.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Where is it available? I tried Chrome Canary and it's not a global there.

**Comment by sholladay** [comment]
Microsoft and Mozilla are [working on it](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/webspeechapiinput/) and have it behind a flag. Chrome has it without a flag but it is currently vendor prefixed as `webkitSpeechRecognition`.

It's the early days, so it's fine if you want to keep this PR on ice for a while. The reason this would be useful to me today is so that ESLint doesn't complain about my feature detection.

**Comment by nzakas** [comment]
I would wait for now. You can always specify your own global either in the configuration file or using an inline comment to satisfy ESLint.

**Comment by sholladay** [comment]
That's what I am doing currently. Works well, just not DRY between projects.

Merging this now would probably be jumping the gun, but it's here if / when you want it.

**Comment by sindresorhus** [comment]
Closing as it still isn't in any browsers.

**Pull request closed without merging**
