### PR TITLE
Add `mocha` to `mocha` environment

### PR DESCRIPTION
**Pull request by BYK**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why?

**Comment by BYK** [comment]
Because `mocha` defines itself as a global and you may use it to configure
it as we did in our project?

**Comment by sindresorhus** [comment]
Ok, that's why I'm asking. Didn't know the global was exposed and never seen it used. Cool.

**Comment by sindresorhus** [comment]
Weird that nobody complained about it on JSHint https://github.com/jshint/jshint/blob/e6611af2d180bd2317d5762e85807a481de99ccb/src/vars.js#L672 They've had the `mocha` option for a year now.

**Comment by sindresorhus** [comment]
@BYK Would be awesome if you could fix this on JSHint too ;)

**Comment by BYK** [comment]
>Weird that nobody complained about it on JSHint https://github.com/jshint/jshint

I was quite surprised to find out when ESLint complained about this :D

>@BYK Would be awesome if you could fix this on JSHint too ;)

Sure, why not? That said I think people should move onto ESLint ;)

**Comment by BYK** [comment]
Here you go: jshint/jshint#2441

**Pull request merged**
