### PR TITLE
Drop the builtin category and move the missing variables to appropriate es* categories (#140)

### PR DESCRIPTION
**Pull request by Standard8**
This implements what was outlined in #140. The only missing items in the es* categories were the `BigInt` related ones, and the `globalThis`.

I have put them in the `es2017` section as that is the latest one there. I wasn't quite sure if that was right or not.

### CODE REVIEW

**Comment by Standard8** [comment]
Looking at the ESLint version of the configuration file, do we actually want a es2020 section now?

https://github.com/eslint/eslint/blob/fee6acbe13cecd4c028e681e185fc6a6d6ba9452/conf/environments.js#L35

**Comment by sindresorhus** [comment]
> do we actually want a es2020 section now?

Yup

**Comment by nzakas** [comment]
I’d prefer not to drop builtin completely. It can be generated from the other categories to keep it in sync if that’s the concern. I think it’s valuable to keep as a collection of all globals.

**Comment by brettz9** [comment]
@Standard8 , is anything holding you back from moving the three `BigInt*` and `globalThis` to a new `es2020` (and restoring the `builtin` section)?

**Comment by sindresorhus** [comment]
Closing for lack of response.

https://github.com/sindresorhus/globals/issues/140#issuecomment-701028864

**Pull request closed without merging**
