### PR TITLE
Add `SharedArrayBuffer` to new ES8 section

### PR DESCRIPTION
**Pull request by addaleax**
List `SharedArrayBuffer`, since with V8 6.2 having landed in Node.js master, this is definitely available in Node 9 and quite possibly future Node 8 releases without a flag.

### CODE REVIEW

**Comment by sindresorhus** [comment]
You put it in `es5`, which is not correct. It's part of the ES2017 draft, so not really sure where to put it. Should at least be put in `builtin`, but maybe we should also create a new `es8` section? // @nzakas @not-an-aardvark

**Comment by addaleax** [comment]
@sindresorhus Yeah, sorry, I meant to put it in es6 since that seemed like the closest match.

**Comment by not-an-aardvark** [comment]
IMO, creating a new `es8` section would be better than putting it in `es6` since it's not specified as part of ES6.

@addaleax Is Node also going to ship with the `Atomics` global? I recall `Atomics` was also introduced in ES8.

**Comment by addaleax** [comment]
@not-an-aardvark Yes, thanks for the pointer; `Atomics` is coming as well.

So, the idea is that I create a duplicate entry to `es6` that’s called `es8` and has those extra entries? I can do that much. :smile:

**Comment by not-an-aardvark** [comment]
Sounds good to me. I think it would be nice to also allow ESLint users to use year-based versions (`es2017` in this case), but ESLint could add that as an alias without needing it to be added to `globals` upstream, so I'm fine with just adding it as `es8` here.

**Comment by sindresorhus** [comment]
> So, the idea is that I create a duplicate entry to es6 that’s called es8 and has those extra entries? I can do that much. 😄

Yes, and also put it in `builtins`.

**Comment by addaleax** [comment]
Does this look like ~ what you had in mind?

**Comment by addaleax** [comment]
@sindresorhus ?

**Pull request merged**
