### PR TITLE
Mocha globals missing 'xdescribe' and 'xit'

### PR DESCRIPTION
**Pull request by valorkin**
fixes https://github.com/eslint/eslint/issues/1737

### CODE REVIEW

**Comment by lo1tuma** [comment]
There is also `xcontext` (alias for `xdescribe`) and `xspecify` (alias for `xit`).

**Comment by valorkin** [comment]
@lo1tuma accordingly to mocha bdd interface added all aliases
mocha bdd: https://github.com/mochajs/mocha/blob/master/lib/interfaces/bdd.js

**Comment by valorkin** [comment]
@es128 review please :)

**Comment by es128** [comment]
:+1: LGTM

**Comment by nzakas** [comment]
:+1:

**Comment by arthurvr** [comment]
Looks good.

**Pull request merged**
