### PR TITLE
More parity with eslint/jshint

### PR DESCRIPTION
**Pull request by es128**
- Moved the typed arrays to builtin (#2) and added Object.prototype methods (#3)
- Completed the list of test runner globals
- All sections from eslint's list are now included
- Have not included the following sections from jshint so far (let me know if you'd want them added):
  - `browserify` - shouldn't the `node` list should just be used any time this one is desired?
  - `shelljs`, `dojo`, `mootools`, `prototypejs`
- Added to the `browser` list anything that was missing when compared with jshint's version of the list

### CODE REVIEW

**Comment by lennym** [comment]
I just found myself here as a result of pondering on a `browserify`/`commonjs` environment for eslint - with just `require`, `module` and `exports` defined. I was wondering if the decision to not include this in this repo was a firm one, because I personally would find it very useful to be able to eslint browserify'ed code without having to also add all of the `node` globals.

**Comment by es128** [comment]
@lennym so in this scenario you want to be able to reuse the other identifier names used as `node` globals for other purposes and have the linter respond accordingly? Doesn't seem like a great practice to follow. Can you demonstrate a use case where this would make sense?

**Comment by lennym** [comment]
I'm running eslint over code which is run in browser, but uses browserify. Thus I want `require` and `module` to be allowed globals, but not all the additional things which adding `node` as an env also allows.

**Comment by es128** [comment]
In case one accidentally uses a `node` global forgetting where this code is meant to be run? I thought browserify's transforms already took care of this.

**Comment by lennym** [comment]
Yes, I had a play and it seems that you're right. Browserify does seem to "just work" as best as it can with node globals.

I still feel like setting env `node: true` in the eslintrc for files I know aren't going to run in a node env is some severe misdirection, but at least I know it's not going to allow anything which will bring down my app now.

**Pull request merged**
