### PR TITLE
Remove deprecated Jest globals

### PR DESCRIPTION
**Pull request by dmitriiabramov**

### CODE REVIEW

**Comment by nzakas** [comment]
It's probably not a good idea to remove globals that have just been deprecated.

**Comment by dmitriiabramov** [comment]
they've been removed from jest a few month ago, and only stayed there for a few weeks actually.
but we can keep them around for a while :)

**Comment by montogeek** [comment]
Can we take the opportunity to add `fdescribe`?

**Comment by ncuillery** [comment]
> Can we take the opportunity to add fdescribe?

`fail` is missing too.

But... #106

**Pull request merged**
