### PR TITLE
Add MediaStream and RTCPeerConnection for browser environment

### PR DESCRIPTION
**Pull request by johanbrook**
As documented in:

- https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API
- https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection

### CODE REVIEW

**Comment by nzakas** [comment]
It looks like these are not yet standardized and are still in experimental phase. @sindresorhus thoughts?

**Comment by johanbrook** [comment]
Yes, they are still "experimental" in that sense, but as you can see below and above the added lines, there are other APIs added, which also are experimental. 

Here are the W3C Working Drafts:

- http://www.w3.org/TR/mediacapture-streams/#stream-api
- http://www.w3.org/TR/webrtc/#rtcpeerconnection-interface

**Comment by sindresorhus** [comment]
I think we should be pragmatic and add what's in browsers. None of these are in latest Chrome though. Are you actually using these? If so, where?

**Comment by johanbrook** [comment]
Ah, no they seem to be prefixed: `window.webkitRTCPeerConnection` works in Chrome, for instance. Will probably get standardized at some point. But usually, one does

```js
RTCPeerConnection = window.RTCPeerConnection || window.mozRTCPeerConnection || 
                    window.webkitRTCPeerConnection;
```

So the unprefixed name is needed anyway I think.

**Comment by sindresorhus** [comment]
I'm ok with adding these. @nzakas ?

**Comment by nzakas** [comment]
Sounds us.

**Comment by nzakas** [comment]
Oops, stupid autocorrect. Sounds good!

**Comment by johanbrook** [comment]
Thanks!

**Pull request merged**
