### PR TITLE
Add support for Meteor environment

### PR DESCRIPTION
**Pull request by johanbrook**
Meteor sure likes its globals ...

### CODE REVIEW

**Comment by es128** [comment]
Indentation needs to be fixed.

Otherwise, :+1:

**Comment by johanbrook** [comment]
@es128 Sorry, GitHub's online editor decided to do its own thing. Fixed now! :sparkles:

**Comment by johanbrook** [comment]
Eheh, and **bam**: this can't be merged due to https://github.com/sindresorhus/globals/commit/f4830c5dc48e0ac0883980ff3287481711d4b2a7. I'll fix it locally.

**Comment by sindresorhus** [comment]
Agh, sorry about that. Not sure why it's an merge conflict though. You're just adding code to the bottom which I didn't touch.

Can you alpha sort the props while you're at it?

**Comment by johanbrook** [comment]
@sindresorhus No worries. Merged and sorted mine!

**Comment by nzakas** [comment]
:+1:

**Comment by johanbrook** [comment]
Thanks!

**Pull request closed without merging**
