### PR TITLE
Add `atom` global to `atomtest`

### PR DESCRIPTION
**Pull request by danielbayley**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please link to a source. I cannot trust or manually verify every contribution.

**Comment by danielbayley** [comment]
@sindresorhus Sorry don't/didn't you use Atom?
This is simply the global `atom` environment used in just about every package… https://flight-manual.atom.io/api/v1.52.0/AtomEnvironment

**Comment by sindresorhus** [comment]
I use Sublime.

**Comment by danielbayley** [comment]
> I use Sublime.

@sindresorhus Interesting… I was sure I read somewhere in a FAQ or something that you were an Atom user… I'm personally begrudgingly migrating over to VSCode… but still using it for some packages I already built. Anyway cheers!

**Pull request merged**
